### ISSUE TITLE
Problem with vitables on Scientific Linux 6.2

### ISSUE THREAD

**Issue by md23ch** [uvemas/ViTables#37]
Dear All,

I have compiled and installed PyTables and all related packages. Next I have installed Vitables.
When I started Vitables I get the following error:
Traceback (most recent call last):
  File "/usr/bin/vitables", line 105, in <module>
    main(sys.argv)
  File "/usr/bin/vitables", line 91, in main
    vtapp = VTApp(mode=options.mode, dblist=options.dblist, h5files=h5files)
  File "/usr/lib/python2.6/site-packages/vitables/vtapp.py", line 116, in __init__
    dbs_tmodel = dbsTreeModel.DBsTreeModel(self)
  File "/usr/lib/python2.6/site-packages/vitables/h5db/dbsTreeModel.py", line 70, in __init__
    super(DBsTreeModel, self).__init__(parent=None)
AttributeError: 'parent' is not a Qt property or a signal
------------------------------------------------------------------------------
The packages which I have on SL6.2 are as following:
ViTables-2.1
qtwebkit-2.1.1-1.el6.i686
qt-sqlite-4.6.2-26.el6_4.i686
qt-mobility-1.1.3-2.el6.i686
qt-x11-4.6.2-26.el6_4.i686
qt-4.6.2-26.el6_4.i686

python version 2.6.6
python-libs-2.6.6-51.el6.i686
numexpr-2.4
tables-3.1.1
Cython-0.14.1-3.el6.i686
hdf5-1.8.14

I have no idea what could be wrong.

Best Regards

Miroslaw Dach

**Comment by uvemas** [comment]
Hi Miroslaw,

it is the first time this error is reported and right now I have no idea on what the problem can be (although it seems to be related to the PyQt version, 4.6.2 could be too old). I'll try to have some spare time this weekend for thinking about it. I hope to have some news next week. In the meantime you could try to use the repository version of ViTables.

Sorry for not fixing the problem faster but it is really difficult for me to have spare time for devoting to ViTables :-(.

Vicent

**Comment by md23ch** [comment]
Hi Vicent,

Thank you for your quick reply. I am looking forward for some hints what to do in order to have ViTables running on my SL6.2 . 

Many Thanks for your support.

Best Regards

Miroslaw Dach

**Comment by uvemas** [comment]
Hi,

I'm trying to install the ViTables package and its dependencies in a virtual machine running Scientific Linux. Unfortunately it's the first time I use this distro and I'm having problems installing packages.

Could you tell me how to install the HDF5 libraries (other than compiling the source code)? I also would like to know how have you installed PyQT4 (from yum packages? downloading it from the PyQt4 site?) and ViTables (which apparently is not included in the Scientific Linux repos).

Regards

Vicent

**Comment by md23ch** [comment]
Hi Vincent,

As regards hdf5 package I have installed sources and compiled whole project. If you like I can provided with the compiled package for Intel_x86_32.

As regards PyQt4 you can install it being root. Just type: yum install PyQt4.
Vitables I have downloaded from the official page and built it according to the instruction.

I had to also install sources of: numpy, numexpr, Pytables and built them on SL6.2

Best Regards 

Miroslaw Dach

**Comment by uvemas** [comment]
Hi,

thanks for your last comment. I've completed the ViTables 2.1 installation on a virtual machine with:

- SL 7x (SL 6 downloading was incredibly slow on all tested mirrors :-(
- Python 2.7.5
- PyTables 3.1.1
- NumPy 1.9.1
- HDF5 1.8.14
- Zlib 1.2.7
- Sphinx 1.2.3
- Qt 4.8.5
- PyQt 4.10.1

Although ViTables 2.1 has not been tested against PyTables 3.1.1 everything seems to go flawlessly so I still think that the problem is that you are using too old versions of PyQt4. My advice is to upgrade your system and use the software versions listed above. If it is not an option, you could try to download and compile the Qt and PyQt4 (and sip) sources *for the versions mentioned above* instead of using the yum packages (beware that ViTables 2.1 has not been tested against recent releases of PyQt). I also recommend  to use the stable ViTables from the GitHub repository because it fixes several annoying bugs related to the browsing of large tables.

Hope it helps.

Vicent

**Comment by md23ch** [comment]
Hi Vincent,

Thank you for your explanation. I will try to rebuilt from sources PyQt4 and let you know.

Best Regards

Miroslaw Dach

**Comment by uvemas** [comment]
No news from Miroslaw since 2 weeks ago. I assumend the problem has been fixed and close the bug.
