### ISSUE TITLE
Release tag that supports Python 3

### ISSUE THREAD

**Issue by scopatz** [uvemas/ViTables#67]
Hello! I am trying to put together a conda-forge package for vitables.  Right now I am running into the issue that v2.1 only support Python 2. However, it seems like develop should support Python 3.  Is there an expected timeline on when a v2.2 will be tagged? Thanks!

**Comment by uvemas** [comment]
Hi! Actually the repo is somewhat a mess. That's my fault, I have no time to keep it tidy and updated. The develop branch is not very active and the python3-support one is dead. Currently most of PR go to the master branch, which supports Python3, PyTables3 PyQt5 and QtPy so your package should be based on master. At the moment I'm fixing bugs as fast as I can. I suspect/know that there are a few serious/annoying bugs and I'd like to fix them before releasing v2.2 but I don't have a timeline for the release :-( 

Sorry for not being more helpful.

**Comment by ankostis** [comment]
Hi @uvemas, why don't release a beta to pypi?
So interested parties can install it only using `pip install --pre`.

**Comment by scopatz** [comment]
Hi @uvemas, no worries, I fully understand.  To second @ankostis, even a v2.2-pre tag on github would be helpful.

**Comment by uvemas** [comment]
Hi,
first of all sorry for the delay. I've just commited and tagged the latest release. Unfortunately I cannot upload the packages to PyPI:

$ twine.exe upload dist/*                                                                           
Uploading distributions to https://pypi.python.org/pypi                                             
Uploading ViTables-3.0.0.tar.gz                                                                     
[================================] 864987/864987 - 00:00:01                                         
HTTPError: 403 Client Error: You are not allowed to edit 'ViTables' package information for url: htt
ps://pypi.python.org/pypi                                                                           

It seems there is a conflict with the existing ViTables packages, packaged by Alexey Naydenov, and my packages. As he registered the packages first then I cannot upload packages with the same name. I'm trying to contact Alexey in order to fix the problem.

**Comment by scopatz** [comment]
Thanks @uvemas! I have a recipe for conda-forge submitted at conda-forge/stage-recipes#3052. If anyone wants to be a maintainer, please let me know!

Also, I am happy to close this, or if you want to wait for the pypi issue to be resolved, that is OK too.

**Comment by uvemas** [comment]
Hi @scopatz. I don't know conda but Francesc Alted told me a few days ago that it is really nice and is the favorite packaging system among scientists so I'll have a look to it when I have some spare time (maybe next year :-)

**Comment by scopatz** [comment]
Haha!
