### ISSUE TITLE
Add support for PyTables's filenodes

### ISSUE THREAD

**Issue by mivade** [uvemas/ViTables#81]
Currently PyTables filenodes are displayed as an array of integers. It would be nice if ViTables detected that it was a filenode and display as a (byte) string instead. This is detectable via the `NODE_TYPE` attribute with value `file`.

**Comment by uvemas** [comment]
Done in a0852cc. The support is basic, not very sophisticated. A filenode with just 100000 short lines takes about 40 seconds to open on my laptop because a VLArray container needs to be created and populated. Once this is done  you can close and open the filenode as fast as any other dataset. I will try to optimize the current implementation but right now I think it is not easy (but maybe I'm a little bit dense right now :-). Suggestions are welcomed.

**Comment by uvemas** [comment]
Things work better in d45f008. Now a filenode with one million short lines takes about 40 seconds to open for the very first time so opening time has improved one order of magnitude. It is still too poor performance but I hope it helps you. Unfortunately I don't know how to keep improving the performance so I'm closing the bug. Please, let me know if you have some suggestion.
