### ISSUE TITLE
Showing large EArrays is slow

### ISSUE THREAD

**Issue by laborleben** [uvemas/ViTables#86]
Showing large EArray is pretty slow since the buffer is not used and the whole EArray is loaded on each access.

**Comment by uvemas** [comment]
Thanks for your report. Yes, I know that displaying large EArrays is slow, but an EArray is a somewhat difficult object. For instance, your suggested PR fails to show all array elements if the shape is something like (2, 0, 3), where 0 indicates the enlargable dimension. If you can rework your PR so that it works for that kind of shapes I will be really happy merging it.

**Comment by laborleben** [comment]
OK, I understand. I fixed it in the PR. I tested with shapes (2,3,0), (2,0,3), (0,),with StringAtom and UIntAtom, and multiple lengths (zero length to pretty huge arrays). Seems to work for me. Someone adding unit tests would be also great.

**Comment by uvemas** [comment]
Wow! You've been really fast! Many thanks for your PR. And yes, you are right about unit tests. The whole ViTables lacks of unit tests. I'm working on them, but the work progresses slowly.

**Comment by laborleben** [comment]
Thank you!
